### ISSUE TITLE
Crawloverview Maximum Runtime shown as milliseconds 

### ISSUE THREAD

**Issue by amesbah** [crawljax/crawljax#536]
**Describe the bug**

The Crawloverview Configuration shows Maximum Runtime with a number. The number is milliseconds. 

The issue is that it 1) does not show the unit, and 2) milliseconds is not user-friendly.

**Comment by yrahulkr** [comment]
Fixed in f6a4beaf6b8d02f2bdd65d589ab31d4ba61fa73a

**Comment by thc202** [comment]
Would be possible to know the roadmap for the next release?

We are using a forked version of Crawljax (https://github.com/zaproxy/crawljax/) and we would like to integrate some of the changes upstream (some bug fixes and enhancements) to stop using the forked version, if possible. (Some of the bugs were already fixed.)

I opened some PRs recently to get some minor changes in: https://github.com/crawljax/crawljax/pulls/thc202
I see the recent issues were fixed in the `frag` branch, should I update the PRs to target that branch instead of `master`?

**Comment by yrahulkr** [comment]
Thank you for reaching out. We are making some major changes to `crawljax-core` module and are in the process of making a major release - 5.0 

The `frag` branch is under active development and not stable at the moment. We will make a stable release on the `master` branch soon. Sorry, we are unable to provide an exact timeline but we are very close and working on ensuring code quality before we make the release.
